name: Deploy on dev server
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH requirements
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
          sudo chmod 600 ~/.ssh/private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
      - name: checkout
        uses: actions/checkout@v2
      - name: Remove old codes
        run: ssh -i ~/.ssh/private.key github-user@getveri.xyz "rm -fr /home/github-user/dev/veri/veri-*"
      - name: Copy new codes
        run: |
          tar czf - veri-*end | \
          ssh -i ~/.ssh/private.key github-user@getveri.xyz "cd /home/github-user/dev/veri/ && tar xvzf -"
      - name: run update script
        run: ssh -i ~/.ssh/private.key github-user@getveri.xyz "sudo ./automation.sh dev"